build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
checks:
    php:
        code_rating: true
        duplication: true
filter: {  }
coding_style:
    php:
        indentation:
            general:
                use_tabs: true