language: php
dist: trusty

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction

script:
- composer validate --strict
- vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
